### PR TITLE
Fix ConcurrentModificationException whilst sweeping votes

### LINKED ISSUE #139: Exception purging votes
I got these logs today in my Bungee console:

``` 
> [18:16:33 WARN] [NuVotifier]: Purging out of date vote.
> [18:16:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@60e949e1, id=55, owner=com.vexsoftware.votifier.bungee.NuVotifier@5939e24, task=com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache$$Lambda$198/1608357825@3b5a19ed, delay=180000, period=180000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_212]
at com.vexsoftware.votifier.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.remove(AbstractMapBasedMultimap.java:1431) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.serializeMap(FileVoteCache.java:153) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.save(FileVoteCache.java:120) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.lambda$new$0(FileVoteCache.java:33) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [18:19:33 WARN] [NuVotifier]: Purging out of date vote.
> [18:19:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@60e949e1, id=55, owner=com.vexsoftware.votifier.bungee.NuVotifier@5939e24, task=com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache$$Lambda$198/1608357825@3b5a19ed, delay=180000, period=180000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_212]
at com.vexsoftware.votifier.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.remove(AbstractMapBasedMultimap.java:1431) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.serializeMap(FileVoteCache.java:153) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.save(FileVoteCache.java:120) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.lambda$new$0(FileVoteCache.java:33) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [18:22:33 WARN] [NuVotifier]: Purging out of date vote.
> [18:22:33 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@60e949e1, id=55, owner=com.vexsoftware.votifier.bungee.NuVotifier@5939e24, task=com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache$$Lambda$198/1608357825@3b5a19ed, delay=180000, period=180000, running=true) encountered an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.remove(HashMap.java:1459) ~[?:1.8.0_212]
at com.vexsoftware.votifier.google.common.collect.AbstractMapBasedMultimap$AsMap$AsMapIterator.remove(AbstractMapBasedMultimap.java:1431) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.serializeMap(FileVoteCache.java:153) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.save(FileVoteCache.java:120) ~[?:?]
at com.vexsoftware.votifier.support.forwarding.cache.FileVoteCache.lambda$new$0(FileVoteCache.java:33) ~[?:?]
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

### PR DESCRIPTION
**Pull request by astei**
Fixes #139

### CODE REVIEW

File: common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/MemoryVoteCache.java [hunk 1]
```diff
@@ -92,16 +92,20 @@ public void addToCachePlayer(Vote v, String player) {
...
+            cacheLock.unlock();
+        }
     }
 
     private void sweep(Multimap<?, Vote> m) {
         Iterator<Vote> vi = m.values().iterator();
         while (vi.hasNext()) {
             Vote v = vi.next();
             if (hasTimedOut(v)) {
-                l.warn("Purging out of date vote.", v);
```
Comment (Ichbinjoe) [inline common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/MemoryVoteCache.java]: pls don't remove me

Comment (astei) [reply common/src/main/java/com/vexsoftware/votifier/support/forwarding/cache/MemoryVoteCache.java]: Re-added.
